# /etc/greetd/config.toml
[terminal]
vt = 7

[initial_session]
command = "dbus-run-session sway-run"
user = "libor"

[default_session]
# The command to start tuigreet
command = "tuigreet --greeting 'Vítejte ve VoidLinux' --asterisks --time --time-format %c --remember --remember-session --power-reboot 'loginctl reboot' --power-shutdown 'loginctl poweroff' --cmd 'dbus-run-session sway-run'"
# The user that runs the greeter
user = "greeter"


